<a href="https://colab.research.google.com/github/2303A52372/Generative_AI_B40/blob/main/Assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adadelta
from tensorflow.keras.utils import to_categorical



data = pd.read_csv("winequality-red.csv")
X, y = data.drop('quality', axis=1).values, data['quality'].values

num_classes = len(np.unique(y))
y = y - min(y)

y_categorical = to_categorical(y, num_classes=num_classes)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_categorical, test_size=0.2, random_state=42)

# Build and train ANN model
model = Sequential([
    Dense(16, input_dim=X_train.shape[1], activation='relu'),
    Dense(20, activation='relu'),
    Dense(25, activation='relu'),
    Dense(10, activation='relu'),
    Dense(num_classes, activation='softmax')
])
model.compile(optimizer=Adadelta(), loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=50, batch_size=64, validation_split=0.2)
model.save("wine_quality_model.h5")

# Evaluate and calculate metrics
model = load_model("wine_quality_model.h5")
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")
y_pred = np.argmax(model.predict(X_test), axis=-1)
y_test_labels = np.argmax(y_test, axis=-1)
print("Confusion Matrix:\n", confusion_matrix(y_test_labels, y_pred))
print("Classification Report:\n", classification_report(y_test_labels, y_pred, zero_division=1))

# Deploy and predict quality
def predict_quality(input_data):
    model = load_model("wine_quality_model.h5")
    input_data = scaler.transform(np.array(input_data).reshape(1, -1))
    prediction = np.argmax(model.predict(input_data), axis=-1)
    return prediction[0] + min(data['quality'])

# Example usage
sample_data = [7.4, 0.7, 0.0, 1.9, 0.076, 11, 34, 0.9978, 3.51, 0.56, 9.4]
print("Predicted Quality:", predict_quality(sample_data))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.0184 - loss: 1.8545 - val_accuracy: 0.0117 - val_loss: 1.8647
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0217 - loss: 1.8539 - val_accuracy: 0.0117 - val_loss: 1.8644
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0196 - loss: 1.8596 - val_accuracy: 0.0117 - val_loss: 1.8642
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0235 - loss: 1.8535 - val_accuracy: 0.0117 - val_loss: 1.8640
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0213 - loss: 1.8583 - val_accuracy: 0.0117 - val_loss: 1.8637
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0230 - loss: 1.8537 - val_accuracy: 0.0117 - val_loss: 1.8635
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0235 - loss: 1.8385 - val_accuracy: 0.0117 - val_loss: 1.8633
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0216 - loss: 1.8577 - val_accuracy: 0.0117 - val_loss

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0322 - loss: 1.8346  
Test Accuracy: 0.0250
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Confusion Matrix:
 [[  0   0   0   0   0   1]
 [  0   0   0   0   0  10]
 [  1   0   3   0   0 126]
 [  3   0   1   0   0 128]
 [  2   0   0   0   0  40]
 [  0   0   0   0   0   5]]


Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       1.00      0.00      0.00        10
           2       0.75      0.02      0.04       130
           3       1.00      0.00      0.00       132
           4       1.00      0.00      0.00        42
           5       0.02      1.00      0.03         5

    accuracy                           0.03       320
   macro avg       0.63      0.17      0.01       320
weighted avg       0.88      0.03      0.02       320

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
Predicted Quality: 8
